site_name: LeetCode
site_author: juice
site_description: LeetCode Solutions

# repo_name: leetcode
# repo_url: https://github.com/xjasonlyu/leetcode
# edit_uri: 'blob/main/docs/'
# edit_uri_template: 'blob/main/solutions/{path_noext}.py'

copyright: >-
  Copyright &copy;
  <script>document.write(new Date().getFullYear())</script>


theme:
  language: zh
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: white
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.tabs.link
    - content.code.copy
  favicon: images/favicon.ico
  icon:
    logo: fontawesome/brands/leetcode
    repo: fontawesome/brands/github

plugins:
  - search
  - minify:
      minify_html: true
  - tags:
      tags_file: topic-tags.md
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      strict: false

extra:
  analytics:
    provider: cloudflare
    property: !ENV CLOUDFLARE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/globe
      link: https://add1.dev
    - icon: fontawesome/brands/github
      link: https://github.com/hotjuicew
    - icon: fontawesome/brands/leetcode
      link: https://leetcode.cn/u/hotjuicew/


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details

  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Dashboard: index.md
  - Topic Tags: topic-tags.md
  - Solutions:
    - 1. Two Sum: 1.two-sum.md
    - 27. Remove Element: 27.移除元素.md
    - 704. Binary Search: 704.二分查找.md
    - 977. Squares of a Sorted Array: 977.有序数组的平方.md
