name: Publish Site
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          git config --global user.name  '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
      - run: pip3 install -r requirements.txt
      - env:
          CLOUDFLARE_ANALYTICS_KEY: ${{ secrets.CLOUDFLARE_ANALYTICS_KEY }}
        run: python generate.py && mkdocs gh-deploy --force
